In [50]:
import antigravity

# Is Python difficult to learn? 
* UNIX is user-friendly. It's just picky who its friends are. 
* Contrary to popular belief, Unix is user friendly. It just happens to be very selective about who it decides to make friends with.   -- unknown 
* It’s is easy to use - if you’re one of the 2 percent of the population who thinks logically and can read an instruction manual. The other 98 percent of the population would find it very hard to use. -- Leslie Lamport

# Line breaks and semicolons


In [51]:
a = 1; b = 2   
if a > 0: 
    print ("a is positive") ; print("1234")
print(a, b)

a is positive
1234
1 2


# Assignments

In [3]:
d=10
a, b= 1, 2
x=y=z=10

# Docstrings

In [20]:
def foo(x):
    """ a function to compute the square of integer x
    
    Parameters 
    ----------
    
        x: integer
            the number to be squared
    
    Returns 
    -----------
    
        y: integer
            the square of x 
    
    Examples
    ------------
        
    >>> f(1,2,3)
    1
    >>> f(3,4,5)
    4567
    
    """
 
    return y 

# Doctest and good pratices 

* Linux has succeeded not because the original goal was to make it widely portable and widely available, but because it was based on good design principles and a good development model. -- Linus Torvalds, "The Linux edge", Open Sources: Voices from the Open Source Revolution, O'Reilly, 1999 
* Modularize 
* Test each module before 

Why do we define functions? 
* For reusing a snippet of code -- save me from re-typing
* For others to pay to use your function -- so I can be rich and be a happy professor
* For making debugging easier -- aim small, miss small 

In [33]:
def f(a, b, c):
    '''
    
    Examples
    ------------
        
    >>> f(1,2,3)
    1
    >>> f(3,4,5)
    4567
    '''
    return (a+b)/c

In [34]:
# Doctest is one way to test from examples in docstrings
import doctest 
doctest.run_docstring_examples(f, globals())



#if __name__ == '__main__':
#    import doctest
#    doctest.testmod()


**********************************************************************
File "__main__", line 20, in NoName
Failed example:
    f(3,4,5)
Expected:
    4567
Got:
    1


# Lists and for-loops

Element-wise iteration 

Read more: iterator

In [53]:
a =[1,2,3]
for i in a:
    i += 1 
print (a)
print (i)

[1, 2, 3]
4


## `enumerate`

In [59]:
a=[11,12,13]
for index, element in enumerate(a): 
    print (index, element)


0 11
1 12
2 13


In [61]:
a =[1,2,3,4,5,6]
for i in a:
    print (i)
    a.remove(i)

1
3
5


In [25]:
a = 3; b= 100
if a > 50:
    print ("a is large enough")
elif a > 5: 
    print ("a is not too large but large enough")
elif a > 2: 
    print ("fine. ")
else: 
    print ("a is NOT large enough")


fine. 


# Tuples

In [28]:
a=[1,2,3]
b=(4,5,6)

TypeError: can only concatenate tuple (not "int") to tuple

## `zip`

In [38]:
c = tuple(zip([1,2,3], [4,5,6])) 
print (c)
d= list(zip(*c))
print (d)

((1, 4), (2, 5), (3, 6))
[(1, 2, 3), (4, 5, 6)]


# Dictionaries

In [56]:
gpa={"yuanzhi":3.7, "gupta":3.5, "john":3.6}
print (gpa["john"])
for name, grade in gpa.items():
    print (name, "'s GPA is: ", grade)
print (gpa.keys())
print (gpa.values())

3.6
yuanzhi's GPA is: 3.7
gupta's GPA is: 3.5
john's GPA is: 3.6
dict_keys(['yuanzhi', 'gupta', 'john'])
dict_values([3.7, 3.5, 3.6])



# Functions

In [57]:
def foo(a, b):
  return a//b, a%b 
foo(70, 12)

(5, 10)

In [64]:
def foo(a,b):
  return a+b
foo(1,2)

3

## Multiple returns
A function with multiple return variables actually returns a tuple. 

In [5]:
def foo(x):
    return x+1, x+2

print (foo(2))
print (foo(2)[0])
print (foo(2)[1])

(3, 4)
3
4


## positional (mandatory) and optional (keyword) arguments 

Positional arguments cannot have default value. Hence, they are mandatory. 
Keyword arguments have default value. Hence, you can ignore them when calling the function or override the default value. 

In [6]:
def foo(x, y=1):
    return x+y

print (foo(2))
print (foo(2, 5))
print (foo(2, y=9))
    

3
7
11


In [ ]:
def bar(a, b, third=1, fourth=0):
    if third: # not the same as if third != None
        return a+b+third
    else:
        return a+b
print (bar(1,2, third=None))
print (bar(1,2,  fourth=1000, third=-1))

3
2


## * and **

In [62]:
# def bar2(a,b,c,d,e,f, v=1, w=2, q=3, l=5): 
def bar2(*must, **optional):
    total = 0 
    for i in must:
        total += i
    print (total)
    for name, value in optional.items():
        total += value
    return total 

# print (bar2(1,2,3,4, v=1 , w=2, ))

def bar3(*args, **kwargs):
    print (args)
    print (kwargs)

print (bar3(1,2,3,4, v=1 , w=2, ))

(1, 2, 3, 4)
{'v': 1, 'w': 2}
None


Behind the scene: positionary arguments are packed into a tuple and keyword arguments are packed into a dictionary.  

In [12]:
bar2(*(1,2), **{"x":3, "y":4})

3


10

## nested functions 

In [13]:
def foo(a,b):
    def  bar(a,b):
        return a//b 
    def  hoo(a,b):
        return a%b 
    return bar(a,b), hoo(a,b)
foo(123,7)
hoo(123, 7)

NameError: name 'hoo' is not defined

## Tying hint
But note that Python interpreter does not enforce typing. You need to use other tools. 


In [65]:
def foo(a:int, b:int) -> int :
    return a + b
foo(1,2)
foo("1233", "345")

False

# Functional programming 
## `map` and dictionary/list/tuple comprehension

In [68]:
def sqrt(a):
    return a**2 

print ( [  sqrt(x)    for x in range(5)   ] )

print (list( map(sqrt, [1,2,3])))

[0, 1, 4, 9, 16]
[1, 4, 9]


## lambda (anonymous) function


In [74]:
(lambda x, y : x+y) (10, 11)
(lambda x, y : x+y) (1, "hello")
(lambda x, y : x+y) ("hello", 1)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

## `reduce`

In [76]:
def plus(a,b): 
    return a+b

import functools 
print (functools.reduce (plus,  [1,2,3,4]))
print (functools.reduce (lambda x, y: (x,y) ,  [1,2,3,4]))

10
(((1, 2), 3), 4)


### dot product using map and reduce 

In [ ]:
a=[1,2,3]; b = [1,2,2]

import operator
list(map(operator.mul, a, b ))
print (functools.reduce(operator.add, map(operator.mul, a, b ) ))

11


## starmap

In [14]:
def foo(a, b):
    return a+b

# standard map 
A, B = [1,2,3,4], [0.1, 0.2, 0.3, 0.4]
print (list(map(foo, A, B)))

# star map 
import itertools
print (list(zip(A, B))) # pair elements of A and B together 
list(itertools.starmap(foo, zip(A, B)))

[1.1, 2.2, 3.3, 4.4]
[(1, 0.1), (2, 0.2), (3, 0.3), (4, 0.4)]


[1.1, 2.2, 3.3, 4.4]

In [ ]:
print (list(zip([1,2,], [3,4,5])))
print (list(map(foo, [1,3], range(10, 15), range(100, 105))))

[(1, 3), (2, 4)]
[111, 115]


## What if I wanna set the same value for keyword arguments? `partial`


In [77]:
def  foo(a, b, c=1, d=1):
    print (a,b,c,d)
foo2 = functools.partial(foo, d=10)
list(map(foo2, [1,2,3], [3,4,5]))

1 3 1 10
2 4 1 10
3 5 1 10


[None, None, None]

In [ ]:
print ( list(map(lambda x:x**0.5, [1,2,34,89]))) 
print (list(map(lambda x, y: x+y , [1,2,3,4], [5,6,7,8])))
print (list(map(lambda x, y: (x, y) , [1,2,3,4], [5,6,7,8])))
print (list(map(lambda x, y, z: x+y+z , [1,2,3,4], [5,6,7,8], [-1, -2, -3, -4])))

[1.0, 1.4142135623730951, 5.830951894845301, 9.433981132056603]
[6, 8, 10, 12]
[(1, 5), (2, 6), (3, 7), (4, 8)]
[5, 6, 7, 8]


# Exception handling 

In [ ]:
def foo(a,b):
    try :
        print (a/b)
    except TypeError: 
        print  ("wrong type")
    except ValueError:
        pass 

foo(1, 2)
foo("a", "b")

0.5
wrong type


# `eval` and `exec` 

In [ ]:
print (eval("1+1")) # an expression only, no statements, return the value of the expression
y = eval("5+2")
print (y)

z = exec("a=1;b=2")  # no return 
print (a)
print (z)

2
7
1
None


# Classes and OOP

In [79]:
class experiments: 
    def __init__(self, url, epochs): # constructor 
        self.url = url
        self.epochs = epochs

    def __str__(self):
        return f"Run experiment {self.epochs} times from {self.url}"

    # def __repr__(self):
    #     return f"Run experiment {self.epochs} times from {self.url}"
    
    def run(self):
        for epoch in range(self.epochs):
            print (self.url)

exp1 = experiments("kaggle.com", 2)
exp1.run()
print (exp1)

kaggle.com
kaggle.com
Run experiment 2 times from kaggle.com


In [ ]:
class advancedExperiments(experiments): # inheritance 
    def runrun(self):
        for epoch in range(self.epochs):
            print (self.url)
            print ("thjis is advanced")

exp2 = advancedExperiments("loser.rocks", 4)
exp2.runrun()

loser.rocks
thjis is advanced
loser.rocks
thjis is advanced
loser.rocks
thjis is advanced
loser.rocks
thjis is advanced


# Parallelization

In [80]:
def foo(x):
    x += 0.1
    return x*x

import multiprocessing
with multiprocessing.Pool() as p:
    p.map(foo, range(10000))



<multiprocessing.pool.Pool state=TERMINATE pool_size=8>


# Selected third-party libraries
* Beautifulsoup [example](https://github.com/forrestbao/pebble/blob/master/webcrawler/ACL2019_download.ipynb)
* NumPy/Scipy
* Matplotlib
* ipywidget
* Matplotlib, `matplotlib.animation`

# Numpy

In [ ]:
import numpy 

In [83]:
L = [1, [2,3 ]]
L = [[1, 2], [3,4]]

print (numpy.array(L))


a= numpy.array([[1,2], 
                [3,4]])
a
type(a)

[[1 2]
 [3 4]]


numpy.ndarray

In [ ]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [ ]:
numpy.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
a*a # hadamard product or element-wise product

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
a@a
# or 
numpy.matmul(a, a)

array([[ 7, 10],
       [15, 22]])

## axes system in Numpy

In [84]:
print (a)
print (a.max(axis=0))
print (a.max(axis=1))

[[1 2]
 [3 4]]
[3 4]
[2 4]


In [ ]:
a= numpy.array([
                [[1,2], 
                 [3,4]], 
                [[5,6], 
                 [7,8]]
               ])
print (a.max(axis=0))
print (a.max(axis=1))
print (a.max(axis=2))

[[5 6]
 [7 8]]
[[3 4]
 [7 8]]
[[2 4]
 [6 8]]


In [29]:
a= numpy.array([[1,2], 
                [3,4]])
print(a)
print (numpy.vstack((a,a))) 
print (numpy.hstack((a,a))) 
print (numpy.stack((a,a), axis=1))

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [1 2]
 [3 4]]
[[1 2 1 2]
 [3 4 3 4]]
[[[1 2]
  [1 2]]

 [[3 4]
  [3 4]]]


## Properly check whether two numpy.ndarray s are the same

In [30]:
numpy.array_equal(a,a)

True

In [31]:
a==a

array([[ True,  True],
       [ True,  True]])

## broadcast
Note in the example below that `a` is a 2D numpy array while `b` is 1D. Mathematically, the product between the two are not defined. 

In [28]:
import numpy
a= numpy.array([[1,2,5], 
                [3,4,6]])
b = numpy.array([-1, 1, 0])

a*b


array([[-1,  2,  0],
       [-3,  4,  0]])

In [86]:
b=numpy.array(range(30))
print (b)
c = b.reshape(5,2,3)
print (c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]]]


## Think matrixly

If you write for-loops when dealing with numpy arrays, something might be wrong. 

In [34]:
a=numpy.array([[1,2], [3,4]])

# Do not do this
row_sum = 0 
for i in range(len(a)):
    row_sum += a[i].max()

print (row_sum)


# Do this: 
sum(a.max(axis=1))


6


6

In [49]:
a=numpy.array([[1,2], [3,4], [5,6]])
numpy.inner(a,a)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])